name: CombatTagPush
version: 0.1
main: com.addongaming.combattag.Push
author: hamgooof
description: Pushes players out side spawn if in combat.
commands:
 combatlog:
  description: Tells you how long left in combat, as well as who you are in combat with
  aliases: [combattag, combattime]